# Generated by Django 2.2.17 on 2020-11-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='work_days',
            new_name='work_years',
        ),
    ]
