# Generated by Django 2.2.17 on 2020-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vedio',
            new_name='Video',
        ),
    ]
